dist: bionic
sudo: required
language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libwebsocketpp-dev
  - sudo apt-get install openssl
  - sudo apt-get install libjsoncpp-dev
  - sudo apt-get install libcurl4-openssl-dev
  - sudo apt-get install libcurlpp-dev
  - sudo ln -s /usr/include/jsoncpp/json/ /usr/include/json


script:
  - mkdir build
  - cd build
  - cmake ..
  - make
